### ISSUE TITLE
C++ Port

### ISSUE THREAD

**Issue by nem0** [Alan-FGR/aelum#2]
:trollface:

**Comment by Alan-FGR** [comment]
besides the :trollface:, this is a real possibility actually. fortunately code is quite portable but there's no C++ lib that comes close to XNA (/FNA/MG) in terms of functionality. Best one I guess is SFML but xplat sucks... I'm not looking forward to rolling out my own solution using SDL+OpenAL+BGFX and other independent libs.

**Comment by Alan-FGR** [comment]
I've started some work on a C++ port using bgfx, ETA: 10783 years though :trollface:
